### ISSUE TITLE
出现ModuleNotFoundError: No module named 'xk_spider'的bug

### ISSUE THREAD

**Issue by Terrifyyyyy** [starwingChen/YNU-xk_spider#1]
报错具体内容：
Traceback (most recent call last):
** IDLE Internal Exception: 
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\idlelib\run.py", line 548, in runcode
    exec(code, self.locals)
  File "C:\Users\AppData\Local\Programs\Python\Python38\YNU-xk_spider-master\xk_spider\run.py", line 3, in <module>
     from xk_spider.AutoLogin import AutoLogin
 from xk_spider.AutoLogin import AutoLogin
除了是Python3.8版本，环境和您配置的一致，

**Comment by Terrifyyyyy** [comment]
您是不是使用的Linux系统？本人是win10 会不会因此出问题？

**Comment by starwingChen** [comment]
把run.py文件移到与xk_spider文件夹同级的目录试试

**Comment by Terrifyyyyy** [comment]
移动run.py文件之后就搞好了，谢谢
